#!/bin/bash

master_bib='/Users/jon/Documents/master.bib'

# Identify the basename of the passed tex file
basename=$(basename $1 .tex)

# If my master.bib file is available on this system...
if test -f $master_bib; then
	# ... we're on Jon's system so use makebib to create refs.bib from master.bib
	echo "Creating refs.bib from $master_bib"
	makebib $basename.tex $master_bib refs.bib
fi

echo "Parsing $basename.tex"
latex -halt-on-error $basename.tex > /dev/null

if test $? != 0; then
	cat $basename.log; exit 1
fi

echo 'Creating bibliography'
biber $basename.bcf > /dev/null

echo 'Typesetting'
latex -halt-on-error $basename.tex > /dev/null

echo "Creating $basename.pdf"
dvipdfm -q $basename.dvi

# Delete any temporary files
for extension in aux bbl bcf blg dvi fff log out run.xml ttt; do
	if test -f $basename.$extension; then
		rm $basename.$extension
	fi
done
